title: Paul's Personal pages
author: Paul Schmeddes
email: pschmeddes@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
# social links
github_username:  pschmeddes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-slate
