build:
    title: OutSystems Best Practices
    input-folder: src
    output-folder: build
    related-title: See Also    
publish:
    url: https://success.outsystems.com/
    root_path: Documentation/Best_Practices
    toc_url: https://success.outsystems.com/
    toc_root_path: Documentation/Best_Practices
    skip_toc_publish: False
